### ISSUE TITLE
Wrong ACL permissions

### ISSUE THREAD

**Issue by sevensolutions** [sevensolutions/nomad-iis#43]
It looks like ACL permissions are still wrong. They are propagating to "Subfolders and files only" but should be "This folder, subfolders and files".

**Comment by sevensolutions** [comment]
Another problem: Sometimes i get "Error: Some or all identity references could not be translated."

**Comment by sevensolutions** [comment]
It looks like we also need to permit IUSR and IIS_IUSRS to make the anonymous user working.

**Comment by ElNinjaNerdT** [comment]
> Another problem: Sometimes i get "Error: Some or all identity references could not be translated."

I always get this error when using a target website.

**Comment by ElNinjaNerdT** [comment]
> ```
> <configuration>
>     <system.webServer>
>         <security>
>             <authentication>
>                 <anonymousAuthentication userName="" />
>             </authentication>
>         </security>
>     </system.webServer>
> </configuration>
> ```

This is not working for me. I get the following error:

```
This configuration section cannot be used at this path. This happens when the section is locked at a parent level. Locking is either by default (overrideModeDefault="Deny"), or set explicitly by a location tag with overrideMode="Deny" or the legacy allowOverride="false".
```

**Comment by sevensolutions** [comment]
Ah ok.. Thanks for the feedback and sorry for the problems you're facing.
You can try to disable the *Directory Security* feature by setting `directory_security = false` in the driver config (See Readme).
In this case the driver will not change any directory permissions.

I'll think about a solution as soon as i have some free time.
Maybe i'll disable this feature until it's stable enough.

Because of the error:
```
This configuration section cannot be used at this path. This happens when the section is locked at a parent level. Locking is either by default (overrideModeDefault="Deny"), or set explicitly by a location tag with overrideMode="Deny" or the legacy allowOverride="false".
```
This happens, if the section is locked on server level.
If you want to change that, you go to the root node in your IIS management console, select "Feature Delegation" and then change the section for anonymous auth to "Read/Write".

**Comment by sevensolutions** [comment]
> > Another problem: Sometimes i get "Error: Some or all identity references could not be translated."
> 
> I always get this error when using a target website.

@ElNinjaNerdT Can you please tell me a little bit about your environment you're testing on?

The following infos would be helpfull:
- driver.iis.iis_version
- os.name
- os.version

You can find them in the Web UI under Cluster > Clients

**Comment by sevensolutions** [comment]
@ElNinjaNerdT You're welcome. Thx for the response.
In version 0.8. i've changed this a bit to match the IIS default. I didn't know about the IUSR-user which is needed for anonymous auth because i don't really use it.

Glad to hear that your problem is solved. If you find this driver helpful, please leave a star on github. :)
