### ISSUE TITLE
Run code that is in the allocation directory

### ISSUE THREAD

**Issue by ElNinjaNerdT** [sevensolutions/nomad-iis#51]
Hi,

I'm trying to understand how this driver works.

I have created a job using the sample_job.hcl example from the repo. This runs and creates an application inside IIS. As the application path is set to the wwwroot directory, it shows the default IIS "start page."

However, I would like it to run my code, which is in the allocation directory.

How can I achieve this?

**Comment by sevensolutions** [comment]
Sorry for the confusion, the example is not very practical.

You can for example use nomads artifact block to download your own app from an artifacts repo, S3 etc.

https://developer.hashicorp.com/nomad/docs/job-specification/artifact

**Comment by ElNinjaNerdT** [comment]
Thanks, this example is much better. However it's still not working due to permission issues as described in #43
